app = "pckblog"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 400
    soft_limit = 200
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 60000
    grace_period = "5s"
    method = "get"
    path = "/health/check"
    protocol = "http"
    restart_limit = 2
    timeout = 2000
    tls_skip_verify = true
